_commit: v0.0.12
_src_path: gh:huxuan/serious-scaffold-python
author_email: i@you_N_G.org
author_name: you_N_G
module_name: misc
package_name: misc
project_description: A batch of Miscellaneous Python Tools
project_name: Miscellaneous Python Tools
repo_name: misc
repo_namespace: misc
