[build-system]
build-backend = "setuptools.build_meta"
requires = [
  "setuptools",
  "setuptools-scm",
]

[project]
authors = [
  {email = "i@you_N_G.org", name = "you_N_G"},
]
classifiers = [
  "Development Status :: 4 - Beta",
  "License :: OSI Approved :: MIT License",
  "Operating System :: OS Independent",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.8",
  "Programming Language :: Python :: 3.9",
]
description = "A batch of Miscellaneous Python Tools"
dynamic = [
  "dependencies",
  "optional-dependencies",
  "version",
]
keywords = [
  "out-of-box",
  "production",
  "project template",
  "template",
]
name = "misc"
readme = "README.md"
requires-python = ">=3.8"

[project.scripts]
misc-cli = "misc.cli:app"

[project.urls]
homepage = "https://github.com/misc/misc/"
issue = "https://github.com/misc/misc/issues"

[tool.coverage.report]
fail_under = 100

[tool.coverage.run]
omit = [
]

[tool.isort]
filter_files = true
profile = "black"

[tool.mypy]
check_untyped_defs = true
disallow_any_unimported = true
disallow_untyped_defs = true
enable_error_code = [
  "ignore-without-code",
]
exclude = [
]
no_implicit_optional = true
show_error_codes = true
warn_return_any = true
warn_unused_ignores = true

[tool.pytest.ini_options]
addopts = "-l -s --durations=0 --cov=src --cov-report term --cov-report xml"
log_cli = true
log_cli_level = "info"
log_date_format = "%Y-%m-%d %H:%M:%S"
log_format = "%(asctime)s %(levelname)s %(message)s"
minversion = "6.0"

[tool.ruff]
extend-ignore = [
  "D203",
  "D204",
  "D213",
  "D215",
  "D400",
  "D404",
  "D406",
  "D407",
  "D408",
  "D409",
  "D413",
]
fix = true
select = ["ALL"]
src = ["src"]

[tool.ruff.per-file-ignores]
"docs/conf.py" = ["INP001"]
"src/\\{\\{ module_name \\}\\}/__init__.py" = ["N999"]
"tests/*" = ["S101"]

[tool.setuptools.dynamic]
dependencies = {file = ["requirements.txt"]}

[tool.setuptools.dynamic.optional-dependencies]
docs = {file = ["requirements/docs.txt"]}
lint = {file = ["requirements/lint.txt"]}
package = {file = ["requirements/package.txt"]}
tests = {file = ["requirements/tests.txt"]}

[tool.setuptools_scm]

[tool.tomlsort]
all = true
in_place = true
trailing_comma_inline_array = true
